version: 0.0
os: linux
files:
  - source: app.py
    destination: /home/ec2-user/
  - source: script/
    destination: /home/ec2-user/script/
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: script/deploy.sh
      timeout: 300
      runas: root