name: Build

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Trigger CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name test_application \
            --deployment-group-name test_deployment_group \
            --s3-location bucket=${{ secrets.S3_BUCKET }},key=myapp.zip,bundleType=zip